// Add the missing fadeInDelay300, fadeInDelay400, and fadeInDelay500 classes
export const animationClasses = {
  fadeIn: 'animate-fadeIn',
  fadeInDelay100: 'animate-fadeInDelay100',
  fadeInDelay200: 'animate-fadeInDelay200',
  fadeInDelay300: 'animate-fadeInDelay300',
  fadeInDelay400: 'animate-fadeInDelay400',
  fadeInDelay500: 'animate-fadeInDelay500',
  fadeInUp: 'animate-fadeInUp',
  fadeInDown: 'animate-fadeInDown',
  zoomIn: 'animate-zoomIn',
  spin: 'animate-spin',
  pulse: 'animate-pulse',
  bounce: 'animate-bounce',
  float: 'animate-float',
  shimmer: 'animate-shimmer',
  slideInLeft: 'animate-slideInLeft',
  slideInRight: 'animate-slideInRight',
  slideInDown: 'animate-slideInDown',
  slideInUp: 'animate-slideInUp',
  heartbeat: 'animate-heartbeat',
};
