// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tadcpandmetbmwmctzil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZGNwYW5kbWV0Ym13bWN0emlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NjYwNDIsImV4cCI6MjA1NjU0MjA0Mn0.yK8y46vh8eIUrmbBn9hRcyHFRmYgCKZzn8Fg1jE69-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);